export const metadata = {
    title: 'About | Next hero',
    description: 'Generated by create next app',
  }
const About = () =>{
    return <div>
        about page
    </div>
}
export default About;