export const metadata = {
    title: 'manage| Dashboard || Next hero',
    description: 'Generated by create next app',
  }
const ManageProducts = () =>{
    return <div>
        manage apps
    </div>
}
export default ManageProducts