import Sidebar from "./sidebar"

export const metadata = {
    title: 'Dashboard || Next hero',
    description: 'Generated by create next app',
  }
const DashboardLayout = ({children}) =>{
    return <div className="flex container">
        <Sidebar></Sidebar>
        {children}
    </div>
}
export default DashboardLayout