export const metadata = {
    title: 'Dashboard || Next hero',
    description: 'Generated by create next app',
  }
const DashboardPage = () =>{
    return <div>
        this is our main page 
    </div>
}
export default DashboardPage